---
title: "Research"
---

We study ecological processes and biogeographical patterns, in the context of human impacts. While we focus on oceans, we often test concepts developed on land in marine systems; working across realms helps to understand the universality of ecological theories and conservation approaches. 

## Climate biogeography

Species around the globe are shifting their ranges in response to climate change, reshuffling ecosystems and challenging paradigms of natural management. Yet species' range shifts are highly variable, perhaps because many ecological and environmental processes besides climate also influence species distributions. Without understanding these other processes and how they interact with one another and with climate, it’s difficult to predict range shifts and make management recommendations. We work to advance our mechanistic understanding of processes that govern species distributions in the Anthropocene, and consequently, our ability to forecast those distributions. Recent and ongoing work in the lab on this topic has:

* Synthesized published literature and historical reports to build a >100-year time-series of range extensions by marine invertebrates in California, finding that they are highly associated with El Niño and the 2014-2016 large marine heatwave ([Sevigny *et al.*, In review](https://doi.org/10.32942/X2T94P)).
* Proposed a new theory to describe "species on the move" responding to global change via temperature gradients experienced both in space and in time, and at various scales from micro to meso to macro ([Fredston, Tingley, *et al.* 2025](https://doi.org/10.1016/j.tree.2025.03.015)).
* Dug into what geographical ranges actually are, and how to tell if they are shifting ([Fredston, preprint](https://doi.org/10.32942/X2QP69)).
* Tested the degree to which range edges of temperate marine fishes are tracking temperature change ([Fredston-Hermann *et al.* 2020](https://doi.org/10.1111/gcb.15035), [Fredston *et al.* 2021](https://onlinelibrary.wiley.com/doi/abs/10.1111/gcb.15614)).
* Described how marine protected areas can be designed to accommodate future range-shifting species ([Fredston-Hermann *et al.* 2018](https://doi.org/10.1111/nyas.13597)). 

## Cumulative human impacts on marine ecosystems

Climate change may transform ecosystems through not only the "press" of gradual warming but also the "pulse" of extreme events like heatwaves. Further, sustainable oceans require managing other human impacts, including runoff and fishing. Runoff---the direct influx of sediments, nutrients, and other forms of pollution carried to coastal oceans from rivers---directly threatens sensitive habitats that are crucial to biodiversity conservation, like coral reefs and seagrass beds. Well-managed fisheries could provide protein with a low greenhouse gas footprint to billions of people and support livelihoods in countless coastal communities. Unfortunately, many fisheries in the world are associated with problematic social or ecological outcomes---or both. We engage with these issues both through primary research and through collaboration and outreach with stakeholders. Past work on this topic includes:

* Finding that demersal marine fish communities do not exhibit a consistent response to marine heatwaves ([Fredston *et al.* 2023](https://doi.org/10.1038/s41586-023-06449-y)) and also do not exhibit consistent biotic homogenization in the face of climate change ([Kitchel *et al.* 2025](https://doi.org/10.1371/journal.pclm.0000659)). 
* Developing operational tools for land-sea management, particularly in data-limited settings ([Brown *et al.* 2019](https://doi.org/10.1111/1365-2664.13331), [Fredston-Hermann *et al.* 2016](https://doi.org/10.3389/fmars.2016.00273)).  
* Collaborating with economists to demonstrate that the biogeographical dynamics of high-value fishery target species like tunas influence whether it is profitable to harvest them to extinction ([Burgess *et al.* 2017](https://doi.org/10.1073/pnas.1607551114)). 

## Open science and meta-science 

We are enthusiastic about open science. To meet planetary challenges, we need to---as Dr. Julia Stewart Lowndes and friends put it---do ["better science in less time"](https://doi.org/10.1038/s41559-017-0160). We strive to implement best practices for open and reproducible science. Beyond the lab, Dr. Fredston has contributed extensively to collaborations aimed at making it easier for the field to do impactful science, from demystifying climate scenarios for marine ecology audiences ([Burgess *et al.* 2023](https://doi.org/10.1093/icesjms/fsad045)) to building a data infrastructure that standardized dozens of publicly-available bottom trawl surveys from around the world ([Maureaud *et al.* 2024](https://doi.org/10.1038/s41597-023-02866-w)) and created an international community of practice around trawl data ([Maureaud *et al.* 2025](https://doi.org/10.1111/csp2.70035)). She has also written about the challenges and opportunities that the open science movement presents to the marine sciences, especially for early-career scientists ([Fredston and Lowndes 2024](https://doi.org/10.1146/annurev-marine-041723-094741)). 

## Recorded talks

To learn more about what we do, check out this selection of recorded talks by Dr. Fredston: 

[*Species on the move!*, UCSC Slugs and Steins, 2025](https://www.youtube.com/watch?v=4Y-0w_ySBnE)

[*Marine heatwaves and changes in biomass and composition of marine fish communities,* 2024 FISHGLOB virtual conference (with Malin Pinsky)](https://youtu.be/37vAXBZ0n7w?si=Yldi9eUkYMRQ8xKo)

[*Process-based forecasting of near-term range shifts in marine species,* 2022 pre-recorded talk](https://youtu.be/B4aVoyzUWCI)

[*R for the Planet*, New York R Conference (September 9, 2021)](https://www.youtube.com/watch?v=S7JGflYoMh0)
