---
title: "Join the lab"
---

Thank you for your interest in joining the lab! UCSC is on the cutting edge of environmental and marine research. Strong support exists for interdisciplinary work and partnerships, via the [Institute for Marine Sciences](https://marinesciences.ucsc.edu/), [NOAA's Southwest Fishery Science Center](https://www.fisheries.noaa.gov/about/southwest-fisheries-science-center), and more. Prospective graduate students are encouraged to explore the Ocean Sciences [prospective student page](https://ocean.ucsc.edu/academics/graduate/), including the [program prerequisites listed here](https://ocean.ucsc.edu/academics/graduate/admissions-prerequisites/).

The Fredston Lab is a computational group that develops and tests hypotheses about the fundamental dynamics of marine ecosystems using theoretical models and Bayesian and frequentist statistics. Successful Fredston Lab members are likely to have an extensive background in math, programming, and statistics; an enthusiasm for oceanography, quantitative ecology, coding, and open science; evidence of independent leadership in projects (via publications, life experiences, or past research); and a genuine commitment to collaboration and interaction within and beyond the lab. Data reuse and synthesis are at the core of our research program. *We do not have a field or a lab program and do not collect primary ecological data.* 

Dr. Fredston is always open to co-developing proposals for fellowships and other externally funded positions. These opportunities are too numerous and rapidly-changing to list, but feel free to contact Dr. Fredston to discuss specific ones you have identified. We also sometimes advertise funded positions for students and postdocs. **In 2025-26, we are [hiring a postdoc for Bayesian modeling of humpback whales](https://recruit.ucsc.edu/JPF02003).**

All prospective lab members should email Dr. Fredston directly, *unless you are applying for an advertised postdoc, in which case please use the UCSC job application website instead*. You should include the following in your email:

1.  A short summary (one paragraph or less) of your background and career goals.
2.  A short summary (one paragraph or less) of why you want to come to UCSC, and to the Fredston lab specifically.
3.  A short summary (one paragraph or less) of a project you are interested in working on. (This is not binding in any way, but will give Dr. Fredston a sense of what you are excited about and how you think. You can alternatively send a research proposal you've written, like an NSF GRFP application.)
4.  Your current CV. Prospective graduate students should also attach all relevant unofficial transcripts and confirm *in the email text* that they meet the [prerequisites for Ocean Sciences at UCSC](https://ocean.ucsc.edu/academics/graduate/admissions-prerequisites/).

This great [guide to emailing prospective PhD advisers](https://doi.org/10.1038/d41586-023-00786-8) by Dr. Hart at UNSW is worth reading, too (and if it's paywalled for you just let Dr. Fredston know and she will send you a copy).
